### ISSUE TITLE
TypeError: jsonServer is not a function

### ISSUE THREAD

**Issue by saeidex** [yracnet/vite-plugin-json-server#1]
failed to load config from vite.config.ts
error when starting dev server:
TypeError: jsonServer is not a function

![image](https://github.com/yracnet/vite-plugin-json-server/assets/112776380/db0280ba-c7bd-4ee2-81bc-4980f55347aa)

**Comment by yracnet** [comment]
Hi, sorry it is a bug of tsup when build the project, could you fix changer the import as

Import { jsonServerPlugin } from "vite-plugin-json-server";

**Comment by yracnet** [comment]
Sorry, confirm the import as


Import { pluginJsonServer } from "...."




// See /src/index.ts
// export const pluginJsonServer = (

**Comment by saeidex** [comment]
### Thanks it's working now ❤️ 

![image](https://github.com/yracnet/vite-plugin-json-server/assets/112776380/032dcfba-c90f-48b3-9b90-79b7b617ef3e)
